# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='dist.proto',
  package='DIDS',
  serialized_pb='\n\ndist.proto\x12\x04\x44IDS\"5\n\x07Station\x12\x0b\n\x03mac\x18\x02 \x01(\t\x12\x0f\n\x07\x62\x65\x61\x63ons\x18\x03 \x01(\x05\x12\x0c\n\x04rssi\x18\x04 \x03(\x05\"*\n\x08Instance\x12\x1e\n\x07station\x18\x01 \x03(\x0b\x32\r.DIDS.Station')




_STATION = descriptor.Descriptor(
  name='Station',
  full_name='DIDS.Station',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='mac', full_name='DIDS.Station.mac', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='beacons', full_name='DIDS.Station.beacons', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rssi', full_name='DIDS.Station.rssi', index=2,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=73,
)


_INSTANCE = descriptor.Descriptor(
  name='Instance',
  full_name='DIDS.Instance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='station', full_name='DIDS.Instance.station', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=75,
  serialized_end=117,
)


_INSTANCE.fields_by_name['station'].message_type = _STATION

class Station(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STATION
  
  # @@protoc_insertion_point(class_scope:DIDS.Station)

class Instance(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INSTANCE
  
  # @@protoc_insertion_point(class_scope:DIDS.Instance)

# @@protoc_insertion_point(module_scope)
